version 1.0.4 including automatic document creation

diff --git a/GGI_TLM/TEMPLATE_PROJECT/run_automatic_test b/GGI_TLM/TEMPLATE_PROJECT/run_automatic_test
--- a/GGI_TLM/TEMPLATE_PROJECT/run_automatic_test
+++ b/GGI_TLM/TEMPLATE_PROJECT/run_automatic_test
@@ -1,33 +1,46 @@
 #!/bin/bash
 
-## GGI_TLM_DIRECTORY must be set appropriately so that the executables are in
+## If you are running anywhere else then GGI_TLM_DIRECTORY must be set appropriately so that the executables are in
 ## ${GGI_TLM_DIRECTORY}/bin
-## EXAMPLE:GGI_TLM_DIRECTORY=/home/chris/GGI_TLM/GGI_TLM
+## EXAMPLE:
+#GGI_TLM_DIRECTORY=/home/chris/SOFTWARE/GGI_TLM/GGI_TLM
 
 GGI_TLM_DIRECTORY=/home/chris/GGI_TLM/GGI_TLM
+
+export GGI_TLM_DIRECTORY
 
 source ${GGI_TLM_DIRECTORY}/run_configuration_data
 
 EXECUTABLE_DIR="${GGI_TLM_DIRECTORY}/bin"
+SRC_DIR="${GGI_TLM_DIRECTORY}/SRC"
+TEST_DATA_DIRECTORY="${GGI_TLM_DIRECTORY}/TEST_DATA"
 
 MPI_SOLVER_NAME="GGI_TLM_MPI"
 
 SEQ_SOLVER_NAME="GGI_TLM_SEQ"
 
+echo " TEST_DATA_DIRECTORY : ${TEST_DATA_DIRECTORY} "
 echo " GGI_TLM_DIRECTORY   : ${GGI_TLM_DIRECTORY} "
 echo " EXECUTABLE_DIRECTORY: ${EXECUTABLE_DIR} "
 
+export GGI_TLM_DIRECTORY
 export EXECUTABLE_DIR
+export SRC_DIR
+export TEST_DATA_DIRECTORY
 export MPI_SOLVER_NAME
 export MPI_RUN_COMMAND
 export SEQ_SOLVER_NAME
 export SEQ_RUN_COMMAND
-export GGI_TLM_DIRECTORY
 
 echo "Automatic testing of GGI_TLM"
 echo " "
 
+
 FULL_TEST_CASE_LIST="
+TEMPLATE_PROBLEM
+"
+
+QUICK_TEST_CASE_LIST="
 TEMPLATE_PROBLEM
 "
 
@@ -41,11 +54,15 @@ action=run_seq NAME       : run GGI_TLM_SEQ on the test case NAME sequentially t
 action=run_mpi np NAME    : run GGI_TLM_MPI on the test case NAME using mpi on np processors then post process results
 action=post_process NAME  : post process results
 action=clean NAME         : remove all existing results
+action=clean_all NAME     : remove all existing results and saved results
 action=plot NAME          : plot the results to screen
 action=plot_jpg NAME      : plot the results to jpeg file
 action=plot_ref NAME      : plot the results against reference results to screen
 action=plot_ref_jpg NAME  : plot the results against reference results to jpeg file
 action=reference  NAME    : update the reference results with the current set of results
+action=check_reference  NAME    : Check the reference results against the current set of results to see whether they are the same
+action=document  NAME     : Create a document in rtf format with details of the problem i.e. geometry, materials, cables, mesh and results
+action=save  NAME  TAG   : Create a directory RESULTS_TAG and save results, .inp file, .info file and any .rtf files into it.
 
 NAME can be : One of the existing test cases ,
      	    : FULL_TEST_CASE_LIST to run all the test cases
@@ -54,7 +71,7 @@ Existing test cases are:
 
 $FULL_TEST_CASE_LIST
 "
- 
+
 if [ "$#" = "0" ] ; then
 
   echo "$ERROR_STRING"
@@ -104,7 +121,11 @@ else
   if [ "$NAME" = "FULL_TEST_CASE_LIST" ] ; then
   
     TEST_CASE_LIST=$FULL_TEST_CASE_LIST
-      
+  
+  elif [ "$NAME" = "QUICK_TEST_CASE_LIST" ] ; then
+  
+    TEST_CASE_LIST=$QUICK_TEST_CASE_LIST
+    
   elif [ "$NAME" ] ; then
   
     TEST_CASE_LIST=$NAME
@@ -113,6 +134,11 @@ else
   else 
   
     TEST_CASE_LIST=$FULL_TEST_CASE_LIST
+    
+#    echo "No test case(s) specified"
+#    echo " "
+#    echo "$ERROR_STRING"  
+#    exit 1
     
   fi
   
@@ -134,42 +160,60 @@ else
       echo "RUNNING TEST CASE: ${TEST_CASE}"
     
       cd $TEST_CASE
+      
      
       if [ "$ACTION" = "run_mpi" ] ; then
      
-        ./run_automatic_test $ACTION $NP $NAME
+        ./run_automatic_test $ACTION $NP $TEST_CASE
      
       elif [ "$ACTION" = "run_seq" ] ; then
      
-        ./run_automatic_test $ACTION $NAME
+        ./run_automatic_test $ACTION $TEST_CASE
               
       elif [ "$ACTION" = "post_process" ] ; then
        
-        ./run_automatic_test $ACTION $NAME
+        ./run_automatic_test $ACTION $TEST_CASE
              
       elif [ "$ACTION" = "clean" ] ; then
        
-        ./run_automatic_test $ACTION $NAME
+        ./run_automatic_test $ACTION $TEST_CASE
+             
+      elif [ "$ACTION" = "clean_all" ] ; then
+       
+        ./run_automatic_test $ACTION $TEST_CASE
     
       elif [ "$ACTION" = "plot" ] ; then
        
-        ./run_automatic_test $ACTION $NAME
+        ./run_automatic_test $ACTION $TEST_CASE
     
       elif [ "$ACTION" = "plot_jpg" ] ; then
        
-        ./run_automatic_test $ACTION $NAME
+        ./run_automatic_test $ACTION $TEST_CASE
        
       elif [ "$ACTION" = "plot_ref" ] ; then
        
-        ./run_automatic_test $ACTION $NAME
+        ./run_automatic_test $ACTION $TEST_CASE
        
       elif [ "$ACTION" = "plot_ref_jpg" ] ; then
        
-        ./run_automatic_test $ACTION $NAME
+        ./run_automatic_test $ACTION $TEST_CASE
       
       elif [ "$ACTION" = "reference" ] ; then
        
-        ./run_automatic_test $ACTION $NAME
+        ./run_automatic_test $ACTION $TEST_CASE
+      
+      elif [ "$ACTION" = "check_reference" ] ; then
+       
+        ./run_automatic_test $ACTION $TEST_CASE
+      
+      elif [ "$ACTION" = "document" ] ; then
+       
+        ./run_automatic_test $ACTION $TEST_CASE
+      
+      elif [ "$ACTION" = "save" ] ; then
+      
+        TAG=$3
+        ./run_automatic_test $ACTION $TEST_CASE $TAG
             
       else 
      
@@ -182,7 +226,15 @@ else
       
       RETURN_CODE=$?
       
-      if [ "$ACTION" != "clean" ] ; then
+      if [ "$ACTION" = "check_reference" ] ; then
+      
+        read LINE < progress
+    
+        cd ..
+	
+        echo "$LINE " >> progress     
+      
+      elif [ "$ACTION" != "clean" ] ; then
       
         read LINE < progress
     
@@ -228,4 +280,3 @@ else
 fi
 
 # we have some arguments to run_automatic_test
-
diff --git a/GGI_TLM/TEST_DATA/run_test_case_include b/GGI_TLM/TEST_DATA/run_test_case_include
--- a/GGI_TLM/TEST_DATA/run_test_case_include
+++ b/GGI_TLM/TEST_DATA/run_test_case_include
@@ -29,6 +29,7 @@ GGI_TLM_memory_usage.txt \
 *vtk* \
 *.txt \
 *.jpeg \
+*.png \
 *.fout* \
 *.tout* \
 *.vmat \
@@ -41,6 +42,7 @@ GGI_TLM_memory_usage.txt \
 *.avi \
 IELF_value.out \
 fort.* \
+save_result \
 "
 
  
@@ -55,12 +57,15 @@ if [ "$#" = "0" ] ; then
   echo "action=run_mpi np NAME    : run GGI_TLM_MPI on the test case NAME using mpi on np processors then post process results"
   echo "action=post_process NAME  : post process results"
   echo "action=clean NAME         : remove all existing results"
+  echo "action=clean_all NAME     : remove all existing results and saved results"
   echo "action=plot NAME          : plot the results to screen"
   echo "action=plot_jpg NAME      : plot the results to jpeg file"
   echo "action=plot_ref NAME      : plot the results against reference results to screen"
   echo "action=plot_ref_jpg NAME  : plot the results against reference results to jpeg file"
   echo "action=reference  NAME    : update the reference results with the current set of results"
   echo "action=check_reference  NAME    : Check the reference results against the current set of results to see whether they are the same"
+  echo "action=document  NAME     : Create a document in rtf format with details of the problem i.e. geometry, materials, cables, mesh and results"
+  echo "action=save  NAME  TAG   : Create a directory RESULTS_TAG and save results, .inp file, .info file and any .rtf files into it."
   echo " "
   echo "NAME can be one of the existing test cases or leave blank to run the whole set"
   echo " "
@@ -89,7 +94,8 @@ else
       echo "run_automatic_test run_mpi  4 NAME"
       echo " "
 
-      exit
+      echo "Error, wanted a number of processors to run on" > ./progress
+      exit 1
   
     else
     # The grep found only 0-9, so it's an integer. 
@@ -128,7 +134,20 @@ else
 
 # get the run_name 
      cd PROBLEM_SPECIFICATION_FILES
+     
+     NUMBER_OF_INPUT_FILES=$(ls *.inp | wc -l)
+     
+     if [ $NUMBER_OF_INPUT_FILES != 1 ] ; then
+       echo " Error: More than one input file found:"
+       ls *.inp
+       echo ""
+       cd ..
+       echo " Error: More than one input file found" > ./progress
+       exit 1
+     fi
+     
      RUN_FILE_NAME=$(ls *.inp)
+     
      cd ..
      RUN_NAME=${RUN_FILE_NAME%\.*}
      echo "TEST_CASE:${TEST_CASE}  RUN_NAME:${RUN_NAME}"
@@ -149,6 +168,16 @@ else
 	      }" > sed_command
 
        sed -f sed_command PROBLEM_SPECIFICATION_FILES/$RUN_NAME.inp > ./$RUN_NAME.inp
+
+# copy input file and all material, cable and mode files to the run directory
+       
+       cp PROBLEM_SPECIFICATION_FILES/$RUN_NAME.inp ./$RUN_NAME.inp
+       cp PROBLEM_SPECIFICATION_FILES/*.vmat .
+       cp PROBLEM_SPECIFICATION_FILES/*.smat . 
+       cp PROBLEM_SPECIFICATION_FILES/*.cable .
+       cp PROBLEM_SPECIFICATION_FILES/*.mode .
+
+# copy any additional files required which may not be specified in a standard format
        
        $COPY_COMMAND
     
@@ -215,6 +244,15 @@ else
        rm -f $CLEANING_LIST
 # clean any existing output files     
        rm -f $RUN_NAME.*
+             
+     elif [ "$ACTION" = "clean_all" ] ; then
+
+# clean any existing problem specification files   
+       rm -f $CLEANING_LIST
+# clean any existing output files     
+       rm -f $RUN_NAME.*
+# remove the RESULTS_TAG directories i.e. any saved results
+       rm -rf RESULTS_*
     
      elif [ "$ACTION" = "plot" ] ; then
      
@@ -342,7 +380,45 @@ else
         fi
 	
       fi
+      
+     elif [ "$ACTION" = "document" ] ; then
 
+# Run python script to create the document
+     
+       pvpython ${SRC_DIR}/GGI_TLM_document.py
+       
+       echo "FINISHED: $TEST_CASE: document" > ./progress
+      
+     elif [ "$ACTION" = "save" ] ; then
+
+       TAG=$3
+       
+# check whether the RESULTS_$TAG directory exists and create it if it doesn't      
+       if [ ! -d "RESULTS_$TAG" ]; then
+  
+         mkdir RESULTS_$TAG
+  
+       fi
+ 
+# copy result files with tag to the RESUTLS directory
+# The results files to save are the same as those saved as reference results in the create_reference_result process
+
+# create a copy results process from the  PROBLEM_SPECIFICATION_FILES/create_reference_result  script
+     
+       echo "{
+              s/PROBLEM_SPECIFICATION_FILES/RESULTS_$TAG/g
+              s/_ref/ /g
+	      }" > sed_command
+
+       sed -f sed_command PROBLEM_SPECIFICATION_FILES/create_reference_result > save_result
+       
+       source save_result
+
+# copy additional results to the RESUTLS directory i.e. the .inp file, .info file and .rtf file (if it exists)
+
+       cp *.inp  RESULTS_$TAG
+       cp *.info RESULTS_$TAG
+       cp *.rtf  RESULTS_$TAG
              
      else 
      
