Add view_mesh process to run_automatic_test script

diff --git a/GGI_TLM/TEST_DATA/run_test_case_include b/GGI_TLM/TEST_DATA/run_test_case_include
--- a/GGI_TLM/TEST_DATA/run_test_case_include
+++ b/GGI_TLM/TEST_DATA/run_test_case_include
@@ -74,6 +74,7 @@ if [ "$#" = "0" ] ; then
   echo "action=plot_ref_jpg NAME  : plot the results against reference results to jpeg file"
   echo "action=reference  NAME    : update the reference results with the current set of results"
   echo "action=check_reference  NAME    : Check the reference results against the current set of results to see whether they are the same"
+  echo "action=view_mesh  NAME     : View the computational mesh; volume materials, surface materials and cables."
   echo "action=document  NAME     : Create a document in rtf format with details of the problem i.e. geometry, materials, cables, mesh and results"
   echo "action=save  NAME  TAG   : Create a directory RESULTS_TAG and save results, .inp file, .info file and any .rtf files into it."
   echo " "
@@ -237,12 +238,45 @@ random_number.dat" >> GGI_TLM_generate_random_numbers_in.txt
          exit 1
        fi
 #       
+#   Check and plot geometry
        $SEQ_RUN_COMMAND $EXECUTABLE_DIR/GGI_TLM_model_checks < run_name.txt
        read LINE < $PROGRESS_FILENAME
        if [ "$LINE" = "FINISHED: GGI_TLM_model_checks" ] ; then
          echo "STATUS: $LINE"
        else
          echo "Failed: $TEST_CASE: GGI_TLM_model_checks"
+         exit 1
+       fi
+#
+#   Check and plot materials
+       echo "$RUN_NAME
+2      ! View volume material cells
+0      ! All materials
+4      ! View surface material faces
+0      ! All materials
+0      ! exit
+" > temp.txt
+       $SEQ_RUN_COMMAND $EXECUTABLE_DIR/GGI_TLM_material_model_checks < temp.txt
+       read LINE < $PROGRESS_FILENAME
+       if [ "$LINE" = "FINISHED: GGI_TLM_material_model_checks" ] ; then
+         echo "STATUS: $LINE"
+       else
+         echo "Failed: $TEST_CASE: GGI_TLM_material_model_checks"
+         exit 1
+       fi
+#
+#   Check and plot cables
+       echo "$RUN_NAME
+2      ! View cable routes (segment based)
+0      ! All cables
+0      ! exit
+" > temp.txt
+       $SEQ_RUN_COMMAND $EXECUTABLE_DIR/GGI_TLM_cable_model_checks < temp.txt
+       read LINE < $PROGRESS_FILENAME
+       if [ "$LINE" = "FINISHED: GGI_TLM_cable_model_checks" ] ; then
+         echo "STATUS: $LINE"
+       else
+         echo "Failed: $TEST_CASE: GGI_TLM_cable_model_checks"
          exit 1
        fi
 #       
@@ -429,6 +463,14 @@ random_number.dat" >> GGI_TLM_generate_random_numbers_in.txt
         fi
 	
       fi
+             
+     elif [ "$ACTION" = "view_mesh" ] ; then
+
+# Run paraview with a startup python script to load the volume material, surface material and cable mesh geometry files
+     
+       paraview --script=${SRC_DIR}/GGI_TLM_view_mesh.py &
+       
+       echo "FINISHED: $TEST_CASE: view_mesh" > ./progress
              
      elif [ "$ACTION" = "document" ] ; then
 
